language: node_js
node_js:
  - 8
  - 10
  - 12
cache:
  directories:
    - node_modules
script:
  - npm run prettier-check
  - npm run flow
  - npm run build
  - npm run test
  - npm run coverage
  - curl -s https://codecov.io/bash | bash
